### ISSUE TITLE
Graph style

### ISSUE THREAD

**Issue by stklik** [OpenKieler/elkjs#1]
I came across your project and I'm interested in using it in my project.
However, I'm not sure how to modify the style of certain parts of the graph.

Is there a way to specify the shape/colour of nodes/ports/labels? 
Is it possible to specify a CSS class within the graph-JSON?

I am trying to do something like this https://codepen.io/anon/pen/GEaOQQ (created with [https://github.com/cytoscape/cytoscape.js](https://github.com/cytoscape/cytoscape.js) ) but use your layout algorithms.

**Comment by spoenemann** [comment]
ELK JS does not take care of any rendering or styling, it just computes graph layouts. If you would like to render the results, have a look at [sprotty](https://github.com/theia-ide/sprotty).

**Comment by jfstephe** [comment]
@spoenemann @stklik 
Hi guys, 
I too was hoping to use this library with cytoscape. I was wondering if @stklik... did you ever get it working?
@spoenemann - does your suggestion to use sprotty mean this won't work with cytoscape? Is this because there's no cytoscape extension for this project?
I'm currently using the Klay layout in cytoscape but I don't like it's random positioning when re-laying out nodes and I'd like to take advantage of bugs that are fixed in elk that I think will help me :-).
Thanks,
John

**Comment by stklik** [comment]
@jfstephe I have given up on cytoscape and use [mxgraph](https://jgraph.github.io/mxgraph/)  instead. I call elkjs to get the positioning and then place it accordingly. There's no need to repeatedly re-position, so I call before display and then let the users modify manually.

So far it's a quick hack that does the necessary things (mxgraph is not very convenient to use). I think I'll try a smarter solution at some point in the future, but there are bigger fish to fry for the moment...

**Comment by spoenemann** [comment]
@jfstephe 

> @spoenemann - does your suggestion to use sprotty mean this won't work with cytoscape? Is this because there's no cytoscape extension for this project?

elkjs should work with any rendering solution. I proposed sprotty because that's one that I'm maintaining myself :-)

**Comment by jfstephe** [comment]
FYI I forked the KlayJs adapter for cytoscape and converted to elkjs [here](https://github.com/jfstephe/cytoscape.js-elk). It just about works but cytoscape doesn't have port support etc so the two don't line up exactly ATM.
