### ISSUE TITLE
Possibility to set max width of the graph

### ISSUE THREAD

**Issue by Jexim** [OpenKieler/elkjs#10]
Do current algorithms have the ability to limit the maximum width of a graph? That construction of the graph not go beyond the given width, but expand in height.

**Comment by uruuru** [comment]
Do you lay out the graph left-to-right or top-to-bottom?

**Comment by Jexim** [comment]
@uruuru left-to-right

**Comment by uruuru** [comment]
There are some options but it depends on the graphs you want to lay out how well they work. 

**Longest Path Layering** 

You can use the [longest path layering](https://github.com/eclipse/elk/blob/master/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/LayeringStrategy.java) algorithm, which guarantees a layout with minimum width, [like so](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAHYQE4AKmAxjkjiXAHQBmwAbtAMpxTAwwCOAFECYHAGd07EJJxEimXLBJhmkvsDg4wWdABkA8gDkA4iO4AVAPqUAglYASpclSgQkEODAgkNWjp66CYAkgDSRsYAakRorhRoJAAMAIwJOEnJAEwZWQDMeSTpZIkkuaWZJIWVSQAs8bUkAKxFAGztJW5JbRXdJG01-QDsioQSSaloALQAfEmj41VpM-PFREtZ2auTG+LL+Tvrm8VHuSfbc0mFJw1XLXsTLUcdJ20v6W8v5-s9Lze-Eh3Nb5IA):
```
layering.strategy: LONGEST_PATH
nodePromotion.strategy: NIKOLOV
```
This gives:
![diagram2](https://user-images.githubusercontent.com/7552459/35624809-62abbd9a-0690-11e8-9d46-c22423b8e93d.png)
Instead of: 
![diagram3](https://user-images.githubusercontent.com/7552459/35624813-64729252-0690-11e8-891b-9e599f6b9002.png)

Note, however, that most of the time the network simplex layerer produces better results. 

**Wrapping**
Or you could use [wrapping](https://github.com/eclipse/elk/blob/master/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/options/WrappingStrategy.java), [like so](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAO5TAAOFMAdmAHQDOc5cOYW6AygJIByAcQAyAUQD6IgCICRaAPRy0AWQCqQgCo8J0kUSI0IBHGhoBGfYeM0ATBaMmAzHasAWNM5MBWDzQBsRQjArUzQAWgA+E1tAq2swyJonGMd4kxcAgiC01JpvZNyc3yA): 
```
wrapping.strategy: SINGLE_EDGE // MULTI_EDGE
aspectRatio: 1.0 
```
![diagram1](https://user-images.githubusercontent.com/7552459/35624543-93e8d8c6-068f-11e8-97f5-32136bef2f0c.png)

**Comment by Jexim** [comment]
@uruuru thank you. The wrapping option give a good result.
