### ISSUE TITLE
Bring children on 1 line

### ISSUE THREAD

**Issue by donpironet** [OpenKieler/elkjs#15]
Is there a way to put all the children on one line if they are not connected?

So I'm having this:

```
{
 id: "root",
 properties: { 'algorithm': 'layered', 'elk.direction': 'RIGHT', 'elk.alignment': 'RIGHT' },
 children: [
  { id: "n1", width: 30, height: 30 },
  { id: "n2", width: 30, height: 30 },
  { id: "n3", width: 30, height: 30 },
  { id: "n4", width: 30, height: 30 },
  { id: "n5", width: 30, height: 30 },
  { id: "n6", width: 30, height: 30 },
  { id: "n7", width: 30, height: 30 },
  { id: "n8", width: 30, height: 30 },
  { id: "n9", width: 30, height: 30 },

 ],
 edges: [ ]
}
```

What I now get is a 3 x 3 matrix. I thought because of adding the elk.alignment I would get a 1 x 9 matrix. Is it possible that when there are no connections that they are on 1 line?

**Comment by uruuru** [comment]
Try setting `elk.aspectRatio` to a small value, 0.1, for instance.

Since your nodes are not connected, the box layouter is used to position
the separate subgraphs. And it tries to position then to roughly match the
specified aspect ratio.

Alternatively you could set `elk.direction: DOWN` and
`separateConnectedComponents: false`.

**Comment by uruuru** [comment]
... a large value ... :)

**Comment by donpironet** [comment]
Thanks works :-) with down & separateConnectedComponents false

**Comment by pikawolfy** [comment]
Can you set the children of children (i.e. nested children) to be aligned like this, but leave the parent nodes where their layout was calculated? e.g. some nodes, with vertical columns of children nodes within them.

**Comment by uruuru** [comment]
You can set the aspectRatio option for each parent of children
individually.

**Comment by uruuru** [comment]
When hierarchy handling is set to `INCLUDE_CHILDREN` the _whole_ graph is laid out using the layered algorithm. For the aspect ratio configuration to work, the [_box layouter_ ](https://www.eclipse.org/elk/reference/algorithms/org-eclipse-elk-box.html) must be active, though. You can explicitly stop `INCLUDE_CHILDREN` at certain parent nodes like so:

```
{
  id: "root",
  layoutOptions: { hierarchyHandling: 'INCLUDE_CHILDREN' },
  children: [{
    id: 'innerParent',
    layoutOptions: { 
      'hierarchyHandling': 'SEPARATE_CHILDREN',
      'elk.aspectRatio': 10  
    },
    children: [
      { id: "n1", width: 30, height: 30 },
      { id: "n2", width: 30, height: 30 },
      { id: "n3", width: 30, height: 30 },
      { id: "n4", width: 30, height: 30 },
      { id: "n5", width: 30, height: 30 },
      { id: "n6", width: 30, height: 30 },
      { id: "n7", width: 30, height: 30 },
      { id: "n8", width: 30, height: 30 },
      { id: "n9", width: 30, height: 30 },
    ]
  }]
}
```
Node that this will prevent hierarchical edges from working within the subgraph for which handling is deactivated.

**Comment by pikawolfy** [comment]
Upon assigning SEPARATE_CHILDREN to the parent nodes, I get an error 'cannot read property 'p' of null'.

For more context, without this change, the graph looks like this. As you can see, edges are routed to/from the nested nodes, and not the parent nodes. But I want the nested nodes to stack in one column.

![hierarchy](https://user-images.githubusercontent.com/17858802/41988656-aa88789a-79f1-11e8-81ea-d975484b55cc.png)

**Comment by pikawolfy** [comment]
Update:

I only get the propertyMap error mentioned above when I set hierarchyHandling on both the graph and parent nodes (i.e. "separate" on one and "include" on the other). I can set one or the other and the graph renders, although not correctly. 

Graph layout properties:
      layoutOptions: {
        'elk.algorithm': 'layered',
        'elk.layered.feedbackEdges': true,
        'elk.spacing.nodeNode': 10,
      },

with parent node properties:
 layoutOptions: {
          'elk.hierarchyHandling': 'SEPARATE_CHILDREN',
          'elk.separateConnectedComponents': false,
        }

results in this, which has the nodes looking the way we'd like them too, but there are no edges / positions being generated without 'INCLUDE_CHILDREN' on the graph:

![hierarchy2](https://user-images.githubusercontent.com/17858802/41995426-9335ccd2-7a06-11e8-979f-ffe1930cfeb7.png)

**Comment by uruuru** [comment]
The issue with `SEPARATE_CHILDREN` seems odd. Does my example work for you? If so, can you share a preferably small example for which the issue occurs? 

Anyway, looking at your screenshot, using `SEPARATE_CHILDREN` isn't an option since (as you have noticed) you require hierarchical edges to be routed. 

Also, with `separateConnectedComponents` I would have expected the nodes to stack in one column in your case. I'll try to reproduce it myself ...

**Comment by pikawolfy** [comment]
If I run your example, as is, I'm given this layout:

![uluruexample](https://user-images.githubusercontent.com/17858802/42104940-77ceeb94-7b83-11e8-87a0-d1b0770b34ff.png)

Here is an example graph:
`

      id: 'root',
      layoutOptions: {
        'elk.algorithm': 'layered',
        'elk.layered.feedbackEdges': true,
        'elk.hierarchyHandling': 'INCLUDE_CHILDREN'
      },
      children: [
        {
          id: 'n1',
          label: 'n1',
          width: 40,
          height: 50,
          children: [
            {id: 'n1c1', label: 'n1c1', width: 20, height: 20},
            {id: 'n1c2', label: 'n1c2', width: 20, height: 20}
          ],
        },
        {
          id: 'n2',
          label: 'n2',
          width: 40,
          height: 50,
          children: [
            {id: 'n2c1', label: 'n2c1', width: 20, height: 20},
            {id: 'n2c2', label: 'n2c2', width: 20, height: 20},
            {id: 'n2c3', label: 'n2c3', width: 20, height: 20}
          ],
        },
        {
          id: 'n3',
          label: 'n3',
          width: 40,
          height: 50,
          children: [
            {id: 'n3c1', label: 'n3c1', width: 20, height: 20},
          ],
        },
      ],
      edges: [
        {
          id: 'e1',
          sources: ['n1c1'],
          targets: ['n2c1'],
          client: 'n1',
          server: 'n2',
          layoutOptions: {
            'elk.layered.priority.direction': 10,
          },
        },
        {
          id: 'e2',
          sources: ['n1c1'],
          targets: ['n3c1'],
          client: 'n1',
          server: 'n3',
          layoutOptions: {
            'elk.layered.priority.direction': 8,
          },
        },
        {
          id: 'e3',
          sources: ['n2c2'],
          targets: ['n2c3'],
          client: 'n2',
          server: 'n2',
          layoutOptions: {
            'elk.layered.priority.direction': 5,
          },
        },
        {
          id: 'e4',
          sources: ['n2c1'],
          targets: ['n2c1'],
          client: 'n2',
          server: 'n2',
          layoutOptions: {
            'elk.layered.priority.direction': 3,
          },
        },
        {
          id: 'e5',
          sources: ['n2c2'],
          targets: ['n1c2'],
          client: 'n2',
          server: 'n1',
          layoutOptions: {
            'elk.layered.priority.direction': 2,
          },
        },
      ]

which yields this layout (please ignore the 'client' and 'server' fields, those are used for my rendering):

![myexample](https://user-images.githubusercontent.com/17858802/42105006-a99e38a0-7b83-11e8-9f0d-0bac30f2fa77.png)

If I add "SEPARATE_CHILDREN" to the parent nodes, it gives me the 'propertyMap' error. If I add SEPARATE_CHILDREN to the parent nodes but remove INCLUDE_CHILDREN from the overall graph I get this (i.e. no edges are created and node placement is arbitrary):

![myexample2](https://user-images.githubusercontent.com/17858802/42105262-92c805a6-7b84-11e8-929f-df898260302e.png)

And then, if I add "'elk.separateConnectedComponents': false," to each parent node, I get this, again with no edges: 

* It seems that maybe separated components does not cause all of the nested nodes to stack due to feedback edges? Those that get offset to the right are only nodes with sources/targets in the same parent.


![myexample3](https://user-images.githubusercontent.com/17858802/42105337-cd026662-7b84-11e8-901a-67dc6509989f.png)

What I want, is the layout of the first picture I sent, but with nodes stacked vertically, like this (not the best drawing, apologies):

![drawing](https://user-images.githubusercontent.com/17858802/42105864-dde670de-7b86-11e8-8e45-c15871dd4b60.jpg)

**Comment by uruuru** [comment]
I'm still puzzled by parts of the behavior. I'll let you know when I found time to look at the issue more closely. 

One comment though: You probably won't be able to get the edge `n2c2 -> n2c3` without manually creating dummy nodes since the edge leaves and enters the hierarchy without a sensible reason (at least from the layout algorithm's point of view)

**Comment by pikawolfy** [comment]
Hello, again. I wanted to inquire whether you'd had a chance to look into this yet? I'm working on a somewhat-time sensitive project, and hopeful of having this working, if possible.

**Comment by uruuru** [comment]
I'd assume that there are at least two issues here: 
 * IIRC, as soon as `INCLUDE_CHILDREN` is set, the `separateConnectedComponents` option may be overridden internally 
 * dummy nodes that are introduced at points where edge cross hierarchy bounds may explain scenarios like these:
    ```
    -|---o |
     | o---|-
    ```

The first point should at least be documented better, the second point feels like a flaw/something to improve. Maybe @le-cds can put in his two cents and afterwards we could create issues over at elk for it.

**Comment by pikawolfy** [comment]
This perhaps doesn't seem to help the problem that edges aren't being
calculated?
