### ISSUE TITLE
layoutOption `elk.spacing.nodeNode` has no effect

### ISSUE THREAD

**Issue by tylerlong** [OpenKieler/elkjs#19]
```js
const elk = new ELK({
  defaultLayoutOptions: {
    'elk.algorithm': 'layered',
    'elk.direction': 'RIGHT',
   'elk.spacing.nodeNode': 500,
    'elk.layered.spacing.nodeNodeBetweenLayers': 500
  }
})
```

```js
const graph = {
      id: 'root',
      children: [
        {
          id: 'n1',
          width: 100,
          height: 100
        },
        {
          id: 'n2',
          width: 100,
          height: 100
        }
      ]
    }
```

With the code above, spacing between `n1` and `n2` is very small, I expect it to be 500. Did I miss anything?

**Comment by uruuru** [comment]
There's another set of spacing options for the layered layouter that
concern the horizontal spacing: 'layered.spacing.*betweenLayers'.

Your option concerns the vertical spacing.

Maybe that's what you observe?

>

**Comment by uruuru** [comment]
Regarding your edited version: Since there are no edges, the algorithm considers each node to be an individual graph. Each graph is laid out separately and afterwards placed by a dedicated algorithm. There are two ways to alter the behavior you see:

* Change `org.eclipse.elk.spacing.componentComponent`, which affects the spacing between the individual subgraphs (referred to as _components_ in this case)
* Set `org.eclipse.elk.separateConnectedComponents: false`, which prevents the algorithm from treating the subgraphs individually, resulting in the spacing values to actually have an effect for your example

**Comment by tylerlong** [comment]
@uruuru Thank you! I confirm it works.

Both of the following work:

```js
const elk = new ELK({
  defaultLayoutOptions: {
    'elk.algorithm': 'layered',
    'elk.direction': 'RIGHT',
   'elk.spacing.nodeNode': 500,
    'elk.separateConnectedComponents': false
  }
})
```

```js
const elk = new ELK({
  defaultLayoutOptions: {
    'elk.algorithm': 'layered',
    'elk.direction': 'RIGHT',
   'elk.spacing.componentComponent': 500
  }
})
```

**Comment by tylerlong** [comment]
But there is an unexpected behavior: the two nodes are positioned top-down although I set `'elk.direction': 'RIGHT'`.

I know there is not direction because I didn't set any edge. But the original code does lay the two nodes horizontally.  My question is: is there any way to change the "direction" of unconnected nodes?

**Comment by uruuru** [comment]
Yes, you can control that via the 'aspectRatio' option. A large value >>1
will result in a single row, a small value <<1 will result in multiple rows.

>

**Comment by tylerlong** [comment]
That is wonderful! Many thanks!
