### ISSUE TITLE
Why are there different styles to specify layout option values?

### ISSUE THREAD

**Issue by tylerlong** [OpenKieler/elkjs#28]
Let's take `elk.padding` and `elk.position` for example:

```js
{
    "id": "org.eclipse.elk.padding",
    "name": "Padding",
    "description": "The padding to be left to a parent element's border when placing child elements. This can also serve as an output option of a layout algorithm if node size calculation is setup appropriately.",
    "group": "",
    "type": "OBJECT",
    "targets": [
      "PARENTS",
      "NODES"
    ]
  }
```

```js
{
    "id": "org.eclipse.elk.position",
    "name": "Position",
    "description": "The position of a node, port, or label. This is used by the 'Fixed Layout' algorithm to specify a pre-defined position.",
    "group": "",
    "type": "OBJECT",
    "targets": [
      "NODES",
      "PORTS",
      "LABELS"
    ]
  }
```

We can see that both of them are of type `OBJECT`. But when I specify values for them, I need to use two different styles:

```js
 'elk.padding': '[top=25,left=25,bottom=25,right=25]'
```

```js
'elk.position': '(10,20)'
```

A real sample: https://github.com/OpenKieler/elkjs/issues/21#issuecomment-382411657

My question is: why are there two different styles to specify value for `OBJECT` type?

I know that ELK is implemented in Java. And elkjs is auto-generated from ELK Java code. So I think it has something to do with Java serialization and deserialization. 

I have experience with both JS and Java. But I feel lost at the moment. Could you please point me to the right direction so that I can continue my investigation?

**Comment by uruuru** [comment]
In the Java world they are not the same type: `position` is of type `KVector` while `padding` is of type `ElkPadding`. I presume that during the Java to JavaScript transpilation the types are omitted since in the js world all those types are objects (I would have to check though). You can find the actual types in ELK's layout option documentation, for instance for [position](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-position.html). See the _value type_.

Other than that, there are sometimes different ways to specify the same kind of option. They originate from the way `IProperty`s can be parsed. See [`KVector#parse`](https://github.com/eclipse/elk/blob/master/plugins/org.eclipse.elk.core/src/org/eclipse/elk/core/math/KVector.java#L459) for an example. That there are different ways, in particular that there are different styles for different options, is mainly due to historic reasons (options were added by different people etc). Unifying these styles might be something worth looking into in the future.
